# default config
baseurl = "https://testdumps.github.io/testdumps/"
languageCode = "en-us"
title = "Examenus | Free Questions and Answers"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 10

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/quizdown.js"

# navigation
[[menu.main]]
name = "Quiz"
url = "/quiz/"

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 1
hasChildren = true

  [[menu.main]]
  parent = "Categories"
  name = "NJ DMV Knowledge Tests"
  url = "/categories/DMV-knowledge-test/"

# deult parameter #1C344D is logo color
[params]
logo = "images/LogoLight.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "Free Questions and answers for multiple chouice questions from trainings and motor vehicle tests"
# Preloader
preloader = false
# search
search = true
# about author
author = "Admin"
author_image = ""
bio = ""
# Contact info
email = "exmaple@ymail.com"
# Contact Form Action
contact_form_action = "#"
# copyright
copyright = "Copyright &copy; 2021 Examenus.in"

# Instagram feed
[params.instafeed]
enable = false
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
link = ""

[[params.social]]
icon = "ti-github"
link = "#"