backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: testdumps/testdumps
 
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "pages"
    label: "About Sections"
    files:
      - label: "About Section"
        name: "aboutPage"
        file: "content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Enable , name: enable, widget: boolean}
          - {label: Date, name: date, widget: date}
          - {label: Description, name: description, widget: string}
          - {label: Content, name: content, widget: markdown}

      - label: "Center Contact Us Button"
        name: "cta"
        file: "data/en/cta.yml"
        fields:
          - label: Center Contact Us Button
            name: cta
            widget: object
            fields:
              - {label: Title, name: title, widget: string} 
              - {label: Content, name: content, widget: string}
              - {label: Image, name: bg_image, widget: image}
              - {label: Enable , name: enable, widget: boolean}
              - label: button
                name: button
                widget: object
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: Link, name: link, widget: string}
                  - {label: Enable , name: enable, widget: boolean}

      - label: "Contact Us Section"
        name: "contact"
        file: "data/en/contact.yml"
        fields:
          - label: contact
            name: contact
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Sub Title, name: subtitle, widget: string}
              - {label: Content, name: content, widget: string}
              - {label: Enable , name: enable, widget: boolean}
              - label: contact_list
                name: contact_list
                widget: list
                fields:
                  - {label: Icon, name: icon, widget: string}
                  - {label: Info, name: info, widget: string}
              - label: contact_form
                name: contact_form
                widget: object
                fields:
                  - {label: Enable, name: enable, widget: boolean}
                  - {label: Name, name: name, widget: string}
                  - {label: Email, name: email, widget: string}
                  - {label: Subject, name: subject, widget: string}
                  - {label: Message, name: message, widget: string}
                  - {label: Submit, name: submit, widget: string}

      - label: "Social Links"
        name: "Social"
        file: "data/en/social.yml"
        fields:
          - label: social
            name: social
            widget: object
            fields:
              - {label: Enable , name: enable, widget: boolean}
              - label: social_item
                name: social_item
                widget: list
                fields:
                  - {label: Icon, name: icon, widget: string}
                  - {label: Link, name: link, widget: string}
                  - {label: Enable , name: enable, widget: boolean}

  - name: "Blog"
    label: "Analytics"
    files:
      - label: "Banner HomePage"
        name: "banner"
        file: "data/en/banner.yml"
        fields:
          - label: banner
            name: banner
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Enable , name: enable, widget: boolean}
              - {label: Icon, name: icon, widget: string}
              - {label: Content, name: content, widget: text}
              - {label: Image , name: bg_image, widget: image}
              - label: button
                name: button
                widget: object
                fields:
                  - {label: Label, name: label, widget: string}
                  - {label: enable , name: enable, widget: boolean}
                  - {label: Link, name: link, widget: string}