backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: testdumps/testdumps
 
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Section"
        name: "aboutPage"
        file: "content/about.md"
        fields:
          - {label: Title, name: title, widget: string, required: true}
          - {label: Image , name: image, widget: image, choose_url: true, default: "images/author.jpg" }
          - {label: Date, name: date, widget: date, required: true}
          - {label: Description, name: description, widget: string, required: true}
        - label: Content
          name: content
          widget: markdown